/* RISC-V glibc.cpu.hwcaps names.
   Copyright (C) 2026 Free Software Foundation, Inc.
   This file is part of the GNU C Library.

   The GNU C Library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2.1 of the License, or (at your option) any later version.

   The GNU C Library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public
   License along with the GNU C Library; if not, see
   <https://www.gnu.org/licenses/>.  */

/* This file is intentionally included multiple times with different
   RISCV_HWCAP_ENTRY and RISCV_HWCAP_ALIAS macro definitions.  */

#ifndef RISCV_HWCAP_ENTRY
# error "RISCV_HWCAP_ENTRY must be defined before including cpu-hwcaps-list.h"
#endif

#ifndef RISCV_HWCAP_ALIAS
# error "RISCV_HWCAP_ALIAS must be defined before including cpu-hwcaps-list.h"
#endif

RISCV_HWCAP_ALIAS ("vector", RISCV_HWPROBE_IMA_V)

RISCV_HWCAP_ALIAS ("fd", RISCV_HWPROBE_IMA_FD)
RISCV_HWCAP_ALIAS ("c", RISCV_HWPROBE_IMA_C)
RISCV_HWCAP_ALIAS ("v", RISCV_HWPROBE_IMA_V)

RISCV_HWCAP_ENTRY (zba, RISCV_HWPROBE_EXT_ZBA)
RISCV_HWCAP_ENTRY (zbb, RISCV_HWPROBE_EXT_ZBB)
RISCV_HWCAP_ENTRY (zbs, RISCV_HWPROBE_EXT_ZBS)
RISCV_HWCAP_ENTRY (zicboz, RISCV_HWPROBE_EXT_ZICBOZ)
RISCV_HWCAP_ENTRY (zbc, RISCV_HWPROBE_EXT_ZBC)
RISCV_HWCAP_ENTRY (zbkb, RISCV_HWPROBE_EXT_ZBKB)
RISCV_HWCAP_ENTRY (zbkc, RISCV_HWPROBE_EXT_ZBKC)
RISCV_HWCAP_ENTRY (zbkx, RISCV_HWPROBE_EXT_ZBKX)
RISCV_HWCAP_ENTRY (zknd, RISCV_HWPROBE_EXT_ZKND)
RISCV_HWCAP_ENTRY (zkne, RISCV_HWPROBE_EXT_ZKNE)
RISCV_HWCAP_ENTRY (zknh, RISCV_HWPROBE_EXT_ZKNH)
RISCV_HWCAP_ENTRY (zksed, RISCV_HWPROBE_EXT_ZKSED)
RISCV_HWCAP_ENTRY (zksh, RISCV_HWPROBE_EXT_ZKSH)
RISCV_HWCAP_ENTRY (zkt, RISCV_HWPROBE_EXT_ZKT)
RISCV_HWCAP_ENTRY (zvbb, RISCV_HWPROBE_EXT_ZVBB)
RISCV_HWCAP_ENTRY (zvbc, RISCV_HWPROBE_EXT_ZVBC)
RISCV_HWCAP_ENTRY (zvkb, RISCV_HWPROBE_EXT_ZVKB)
RISCV_HWCAP_ENTRY (zvkg, RISCV_HWPROBE_EXT_ZVKG)
RISCV_HWCAP_ENTRY (zvkned, RISCV_HWPROBE_EXT_ZVKNED)
RISCV_HWCAP_ENTRY (zvknha, RISCV_HWPROBE_EXT_ZVKNHA)
RISCV_HWCAP_ENTRY (zvknhb, RISCV_HWPROBE_EXT_ZVKNHB)
RISCV_HWCAP_ENTRY (zvksed, RISCV_HWPROBE_EXT_ZVKSED)
RISCV_HWCAP_ENTRY (zvksh, RISCV_HWPROBE_EXT_ZVKSH)
RISCV_HWCAP_ENTRY (zvkt, RISCV_HWPROBE_EXT_ZVKT)
RISCV_HWCAP_ENTRY (zfh, RISCV_HWPROBE_EXT_ZFH)
RISCV_HWCAP_ENTRY (zfhmin, RISCV_HWPROBE_EXT_ZFHMIN)
RISCV_HWCAP_ENTRY (zihintntl, RISCV_HWPROBE_EXT_ZIHINTNTL)
RISCV_HWCAP_ENTRY (zvfh, RISCV_HWPROBE_EXT_ZVFH)
RISCV_HWCAP_ENTRY (zvfhmin, RISCV_HWPROBE_EXT_ZVFHMIN)
RISCV_HWCAP_ENTRY (zfa, RISCV_HWPROBE_EXT_ZFA)
RISCV_HWCAP_ENTRY (ztso, RISCV_HWPROBE_EXT_ZTSO)
RISCV_HWCAP_ENTRY (zacas, RISCV_HWPROBE_EXT_ZACAS)
RISCV_HWCAP_ENTRY (zicond, RISCV_HWPROBE_EXT_ZICOND)
RISCV_HWCAP_ENTRY (zihintpause, RISCV_HWPROBE_EXT_ZIHINTPAUSE)
RISCV_HWCAP_ENTRY (zve32x, RISCV_HWPROBE_EXT_ZVE32X)
RISCV_HWCAP_ENTRY (zve32f, RISCV_HWPROBE_EXT_ZVE32F)
RISCV_HWCAP_ENTRY (zve64x, RISCV_HWPROBE_EXT_ZVE64X)
RISCV_HWCAP_ENTRY (zve64f, RISCV_HWPROBE_EXT_ZVE64F)
RISCV_HWCAP_ENTRY (zve64d, RISCV_HWPROBE_EXT_ZVE64D)
RISCV_HWCAP_ENTRY (zimop, RISCV_HWPROBE_EXT_ZIMOP)
RISCV_HWCAP_ENTRY (zca, RISCV_HWPROBE_EXT_ZCA)
RISCV_HWCAP_ENTRY (zcb, RISCV_HWPROBE_EXT_ZCB)
RISCV_HWCAP_ENTRY (zcd, RISCV_HWPROBE_EXT_ZCD)
RISCV_HWCAP_ENTRY (zcf, RISCV_HWPROBE_EXT_ZCF)
RISCV_HWCAP_ENTRY (zcmop, RISCV_HWPROBE_EXT_ZCMOP)
RISCV_HWCAP_ENTRY (zawrs, RISCV_HWPROBE_EXT_ZAWRS)
RISCV_HWCAP_ENTRY (supm, RISCV_HWPROBE_EXT_SUPM)
RISCV_HWCAP_ENTRY (zicntr, RISCV_HWPROBE_EXT_ZICNTR)
RISCV_HWCAP_ENTRY (zihpm, RISCV_HWPROBE_EXT_ZIHPM)
RISCV_HWCAP_ENTRY (zfbfmin, RISCV_HWPROBE_EXT_ZFBFMIN)
RISCV_HWCAP_ENTRY (zvfbfmin, RISCV_HWPROBE_EXT_ZVFBFMIN)
RISCV_HWCAP_ENTRY (zvfbfwma, RISCV_HWPROBE_EXT_ZVFBFWMA)
RISCV_HWCAP_ENTRY (zicbom, RISCV_HWPROBE_EXT_ZICBOM)
RISCV_HWCAP_ENTRY (zicbop, RISCV_HWPROBE_EXT_ZICBOP)
RISCV_HWCAP_ENTRY (zaamo, RISCV_HWPROBE_EXT_ZAAMO)
RISCV_HWCAP_ENTRY (zalrsc, RISCV_HWPROBE_EXT_ZALRSC)
RISCV_HWCAP_ENTRY (zabha, RISCV_HWPROBE_EXT_ZABHA)
